@startuml
skinparam classArrowColor #444488
skinparam objectBorderColor #444444
skinparam objectBackgroundColor #EDEDED
skinparam classArrowFontStyle bold
skinparam classArrowFontSize 16
skinparam classArrowFontColor #AA4444

object r1
r1 : hunks = 0
r1 : bug_fix = 0
object r2
r1 - r2
r2 : hunks = 0
r2 : bug_fix = 0
object r3
r2 - r3
r3 : hunks = 80
r3 : bug_fix = 0
object r4
r3 - r4
r4 : hunks = 3
r4 : bug_fix = 0
object r5
r4 - r5
r5 : hunks = 1
r5 : bug_fix = 0
object r6
r5 - r6
r6 : hunks = 9
r6 : bug_fix = 1
object r7
r6 - r7
r7 : hunks = 1
r7 : bug_fix = 0
object r8
r7 - r8
r8 : hunks = 2
r8 : bug_fix = 0
object r9
r8 - r9
r9 : hunks = 3
r9 : bug_fix = 0
object r10
r9 - r10
r10 : hunks = 2
r10 : bug_fix = 0
object r11
r10 - r11
r11 : hunks = 2
r11 : bug_fix = 0
object r12
r11 - r12
r12 : hunks = 2
r12 : bug_fix = 0
object r13
r12 - r13
r13 : hunks = 3
r13 : bug_fix = 0
object r14
r13 - r14
r14 : hunks = 1
r14 : bug_fix = 0
object r15
r14 - r15
r15 : hunks = 2
r15 : bug_fix = 0
r3 : causes = r13 (1/10,w=0.0)
r3 : causes = r5 (1/10,w=0.0)
r3 : causes = r6 (1/10,w=1.0)
r3 : causes = r10 (1/10,w=0.0)
r3 : causes = r8 (1/10,w=0.0)
r3 : causes = r4 (1/10,w=0.0)
r3 : causes = r15 (1/10,w=0.0)
r3 : causes = r14 (1/10,w=0.0)
r3 : causes = r12 (1/10,w=0.0)
r3 : causes = r9 (1/10,w=0.0)
r4 : fixes = r3 (1/1)
r3 "r4:1/10\n\n" <... "r3:1/1\n\n" r4 : weight: 0*1/1=0.0\n
r5 : fixes = r3 (1/1)
r3 "r5:1/10\n\n\n" <... "r3:1/1\n\n\n" r5 : weight: 0*1/1=0.0\n\n
r6 : fixes = r3 (1/1)
r3 "r6:1/10\n\n\n\n" <... "r3:1/1\n\n\n\n" r6 : weight: 1*1/1=1.0\n\n\n
r8 : fixes = r3 (1/1)
r3 "r8:1/10\n\n\n\n\n\n" <... "r3:1/1\n\n\n\n\n\n" r8 : weight: 0*1/1=0.0\n\n\n\n\n
r9 : fixes = r3 (1/1)
r3 "r9:1/10\n\n\n\n\n\n\n" <... "r3:1/1\n\n\n\n\n\n\n" r9 : weight: 0*1/1=0.0\n\n\n\n\n\n
r10 : fixes = r3 (1/1)
r3 "r10:1/10\n\n\n\n\n\n\n\n" <... "r3:1/1\n\n\n\n\n\n\n\n" r10 : weight: 0*1/1=0.0\n\n\n\n\n\n\n
r12 : fixes = r3 (1/1)
r3 "r12:1/10\n\n\n\n\n\n\n\n\n\n" <... "r3:1/1\n\n\n\n\n\n\n\n\n\n" r12 : weight: 0*1/1=0.0\n\n\n\n\n\n\n\n\n
r13 : fixes = r3 (1/1)
r3 "r13:1/10\n\n\n\n\n\n\n\n\n\n\n" <... "r3:1/1\n\n\n\n\n\n\n\n\n\n\n" r13 : weight: 0*1/1=0.0\n\n\n\n\n\n\n\n\n\n
r14 : fixes = r3 (1/1)
r3 "r14:1/10\n\n\n\n\n\n\n\n\n\n\n\n" <... "r3:1/1\n\n\n\n\n\n\n\n\n\n\n\n" r14 : weight: 0*1/1=0.0\n\n\n\n\n\n\n\n\n\n\n
r15 : fixes = r3 (1/1)
r3 "r15:1/10\n\n\n\n\n\n\n\n\n\n\n\n\n" <... "r3:1/1\n\n\n\n\n\n\n\n\n\n\n\n\n" r15 : weight: 0*1/1=0.0\n\n\n\n\n\n\n\n\n\n\n\n
r1 : total bug weight = 0.0
r1 : average weight = NaN
r2 : total bug weight = 0.0
r2 : average weight = NaN
r3 : total bug weight = 1.0
r3 : average weight = 0.1
r4 : total bug weight = 0.0
r4 : average weight = NaN
r5 : total bug weight = 0.0
r5 : average weight = NaN
r6 : total bug weight = 0.0
r6 : average weight = NaN
r7 : total bug weight = 0.0
r7 : average weight = NaN
r8 : total bug weight = 0.0
r8 : average weight = NaN
r9 : total bug weight = 0.0
r9 : average weight = NaN
r10 : total bug weight = 0.0
r10 : average weight = NaN
r11 : total bug weight = 0.0
r11 : average weight = NaN
r12 : total bug weight = 0.0
r12 : average weight = NaN
r13 : total bug weight = 0.0
r13 : average weight = NaN
r14 : total bug weight = 0.0
r14 : average weight = NaN
r15 : total bug weight = 0.0
r15 : average weight = NaN
@enduml
