@startuml
skinparam classArrowColor #444488
skinparam objectBorderColor #444444
skinparam objectBackgroundColor #EDEDED
skinparam classArrowFontStyle bold
skinparam classArrowFontSize 16
skinparam classArrowFontColor #AA4444

object r1
r1 : hunks = 3
r1 : bug_fix = 0
r1--f1.txt_r1
f1.txt_r1--f2.txt_r1
f2.txt_r1--f3.txt_r1
object r2
r1 - r2
r2 : hunks = 2
r2 : bug_fix = 0
r2--f1.txt_r2
f1.txt_r2--f2.txt_r2
object r3
r2 - r3
r3 : hunks = 1
r3 : bug_fix = 0
r3--f1.txt_r3
r3 : fixes = r1 (1/2)
r1 : causes = r3 (1/2)
r1 "r3:1/2\n\n" <... "r1:1/2" r3 : weight: 0*1/2=0.0\n\n
r3 : fixes = r2 (1/2)
r2 : causes = r3 (1/2)
r2 "r3:1/2\n" <... "r2:1/2" r3 : weight: 0*1/2=0.0\n
object r4
r3 - r4
r4 : hunks = 1
r4 : bug_fix = 0
r4--f1.txt_r4
r4 : fixes = r1 (1/1)
r1 : causes = r4 (1/2)
r1 "r4:1/2\n\n\n" <... "r1:1/1" r4 : weight: 0*1/1=0.0\n\n\n
object r5
r4 - r5
r5 : hunks = 2
r5 : bug_fix = 1
r5--f1.txt_r5
r5 : fixes = r4 (1/2)
r4 : causes = r5 (1/1)
r4 "r5:1/1\n" <... "r4:1/2" r5 : weight: 1*1/2=0.5\n
f1.txt_r5--f2.txt_r5
r5 : fixes = r2 (1/2)
r2 : causes = r5 (1/2)
r2 "r5:1/2\n\n\n" <... "r2:1/2" r5 : weight: 1*1/2=0.5\n\n\n
object r6
r5 - r6
r6 : hunks = 1
r6 : bug_fix = 1
r6--f1.txt_r6
r6 : fixes = r3 (1/1)
r3 : causes = r6 (1/1)
r3 "r6:1/1\n\n\n" <... "r3:1/1" r6 : weight: 1*1/1=1.0\n\n\n
r1 : total bug weight = 0.0
r1 : average weight = 0.0
r2 : total bug weight = 0.5
r2 : average weight = 0.25
r3 : total bug weight = 1.0
r3 : average weight = 1.0
r4 : total bug weight = 0.5
r4 : average weight = 0.5
r5 : total bug weight = 0.0
r5 : average weight = NaN
r6 : total bug weight = 0.0
r6 : average weight = NaN
@enduml
